"""init

Revision ID: 4cfd35d3ca1b
Revises: 
Create Date: 2026-01-24 18:07:05.668014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cfd35d3ca1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('choice', sa.String(length=100), nullable=False, comment='我选的队伍'),
    sa.Column('winner', sa.String(length=100), nullable=True, comment='胜者，输了或平局时为空'),
    sa.Column('result', sa.String(length=100), nullable=True, comment='"win"/"lose"/"draw"/None'),
    sa.Column('bet_amount', sa.Integer(), nullable=False, comment='投注金额'),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_choice'), 'match', ['choice'], unique=False)
    op.create_table('battle_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('winner', sa.String(length=100), nullable=False),
    sa.Column('loser', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_battle_winner_loser', 'battle_record', ['winner', 'loser'], unique=False)
    op.create_index(op.f('ix_battle_record_loser'), 'battle_record', ['loser'], unique=False)
    op.create_index(op.f('ix_battle_record_winner'), 'battle_record', ['winner'], unique=False)
    op.create_table('match_team',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('odds', sa.Float(), nullable=True, comment='倍率'),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_team_name'), 'match_team', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_team_name'), table_name='match_team')
    op.drop_table('match_team')
    op.drop_index(op.f('ix_battle_record_winner'), table_name='battle_record')
    op.drop_index(op.f('ix_battle_record_loser'), table_name='battle_record')
    op.drop_index('idx_battle_winner_loser', table_name='battle_record')
    op.drop_table('battle_record')
    op.drop_index(op.f('ix_match_choice'), table_name='match')
    op.drop_table('match')
    # ### end Alembic commands ###
